spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/authentication-demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: miaoqi
  session:
    store-type: none


server:
  port: 8060
security:
  basic:
    enabled: true

imooc:
  security:
    browser:
      #      loginPage: /demo-signIn.html
      loginType: JSON
    code:
      image:
        length: 6
        width: 100
        url: /user/*
      sms:
        url: /xxxxx